In [1]:
import torch

In [2]:
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print("Values: \n{}".format(x))

8. Верните.пакетное.произведение.трехмерной.и.двумерной.матриц.(a=torch.rand(3,4,5),.b=torch.rand(5,4)).


1. Создайте.двумерный.тензор,.после.чего.добавьте.в.него.новое.измерение.размером.1.перед.измерением.0.

In [86]:
x = torch.rand(2, 2)
x.shape

torch.Size([2, 2])

In [87]:
x = x.unsqueeze(0)
x.shape

torch.Size([1, 2, 2])

2. Удалите.дополнительное.измерение,.которое.вы.только.что.добавили.в.предыдущий.тензор.

In [88]:
x = x.squeeze(0)
x.shape

torch.Size([2, 2])

3. Создайте.случайный.тензор.формой.5.×.3.в.интервале.[3,.7).

In [104]:
x = torch.rand((5,3)) * (7 - 3) + 3
x

tensor([[3.9844, 4.2826, 6.4463],
        [5.5664, 4.4016, 6.1330],
        [6.8469, 4.8899, 6.1375],
        [5.8175, 6.0924, 3.8606],
        [6.5317, 4.1920, 5.9994]])

4. Создайте.тензор.со.значениями,.взятыми.из.нормального.распределения (математическое.ожидание.=.0,.стандартное.отклонение.=.1).

In [114]:
torch.Tensor(3, 3).normal_(0, 1)

tensor([[-1.3839, -2.1957, -1.3856],
        [ 0.8153,  1.3229, -0.6353],
        [ 0.0093, -0.3579,  0.2353]])

5. Извлеките.индексы.всех.ненулевых.элементов.из.тензора.torch.Tensor([1,.1,.
1,.0,.1]).

In [119]:
x = torch.Tensor([1, 1, 1, 0, 1])

In [123]:
nx = (x != 0).numpy()

In [135]:
nx.nonzero()[0]

array([0, 1, 2, 4])

6. Создайте.случайный.тензор.размером.(3,1),.а.затем.горизонтально.разместите.в.ряд.четыре.его.копии.

In [137]:
x = torch.rand(3, 1)

In [146]:
x.expand(3, 4)

tensor([[0.3483, 0.3483, 0.3483, 0.3483],
        [0.6201, 0.6201, 0.6201, 0.6201],
        [0.6366, 0.6366, 0.6366, 0.6366]])

In [139]:
torch.cat([x, x, x, x], dim=1)

tensor([[0.3483, 0.3483, 0.3483, 0.3483],
        [0.6201, 0.6201, 0.6201, 0.6201],
        [0.6366, 0.6366, 0.6366, 0.6366]])

7. Верните.пакетное.произведение.двух.трехмерных.матриц.(a=torch.rand(3,4,5),.b=torch.rand(3,5,4)).

In [141]:
a=torch.rand(3,4,5)
b=torch.rand(3,5,4)

In [147]:
torch.bmm(a, b)

tensor([[[1.5098, 0.8145, 1.2376, 0.9374],
         [1.4803, 1.1709, 1.5726, 1.0644],
         [1.2736, 1.0080, 1.7419, 1.5121],
         [1.1323, 0.7094, 1.2143, 1.0179]],

        [[1.7494, 1.8616, 1.9377, 0.4964],
         [1.1961, 1.9112, 1.7052, 0.2892],
         [1.0254, 0.8522, 1.1063, 0.3222],
         [1.3654, 1.5672, 1.7054, 0.4136]],

        [[1.1891, 1.7856, 1.1277, 1.0117],
         [0.7270, 1.1499, 0.6982, 1.1460],
         [0.7687, 1.3146, 0.8661, 1.1494],
         [1.1524, 2.2619, 1.5295, 2.2037]]])